# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aa8bc2f0-8e17-42bf-a83a-5ac92e7a3f30";
      fsType = "btrfs";
      options = [ "subvol=@,noatime,compress-force=zstd:3,ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/aa8bc2f0-8e17-42bf-a83a-5ac92e7a3f30";
      fsType = "btrfs";
      options = [ "subvol=@home,noatime,compress-force=zstd:3,ssd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/aa8bc2f0-8e17-42bf-a83a-5ac92e7a3f30";
      fsType = "btrfs";
      options = [ "subvol=@nix,noatime,compress-force=zstd:3,ssd" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/aa8bc2f0-8e17-42bf-a83a-5ac92e7a3f30";
      fsType = "btrfs";
      options = [ "subvol=@swap,ssd" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
