# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_generic" "ehci_pci" "ahci" "firewire_ohci" "xhci_pci" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/336f90b8-ca8b-4042-a236-f9e6759f1673";
      fsType = "btrfs";
      options = [ "subvol=@,noatime,compress-force=zstd:3,ssd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/336f90b8-ca8b-4042-a236-f9e6759f1673";
      fsType = "btrfs";
      options = [ "subvol=@nix,noatime,compress-force=zstd:3,ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/336f90b8-ca8b-4042-a236-f9e6759f1673";
      fsType = "btrfs";
      options = [ "subvol=@home,noatime,compress-force=zstd:3,ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5EE9-01AF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
